plugins {
    id 'application'
}

dependencies {
    implementation libs.javaparser
    implementation libs.json
    implementation libs.gigachat

    testImplementation libs.junit
    testRuntimeOnly libs.junit.platform.launcher
}

application {
    mainClass = 'com.gigachat.unit.tests.generator.MainAgentEntry'
}

tasks.named('run').configure {
    workingDir = project.rootProject.projectDir
}

java {
    withJavadocJar()
    withSourcesJar()
}

tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
}

tasks.register('MainAgentEntry.main', JavaExec) {
    group = 'application'
    description = 'Runs com.gigachat.unit.tests.generator.MainAgentEntry directly.'
    mainClass = 'com.gigachat.unit.tests.generator.MainAgentEntry'
    classpath = sourceSets.main.runtimeClasspath
    workingDir = project.rootProject.projectDir
}